[config]
version_check = false

[templates.vicinae]
input_path = '~/.config/matugen/templates/vicinae/vicinae.json'
output_path = '~/.config/vicinae/themes/noctalia/noctalia.json'
post_hook = 'vicinae vicinae://theme/set/noctalia'
